package me.strand.error;

import lombok.Getter;

@Getter
public enum ErrorCode {
    // POST REQUESTS
    INVALID_POST_FORMAT("20000"),
    INVALID_COMMENT_FORMAT("20001"),
    COMMENT_INSERTION_FAILED("20002"),
    POST_TITLE_EMPTY("20003"),
    POST_CONTENT_EMPTY("20004"),
    COMMENT_CONTENT_EMPTY("20005"),
    INSERT_SECTION_FAILED("20006"),
    INSERT_SUBSECTION_FAILED("20007"),

    // PUT REQUESTS
    UPDATE_SECTION_FAILED("30000"),
    UPDATE_SUBSECTION_FAILED("30001"),

    // DELETE
    DELETE_SECTION_FAILED("40000"),
    DELETE_SUBSECTION_FAILED("40001"),

    // SECURITY
    CLASS_NOT_SUPPORTED("50000"),

    // APACHE KAFKA
    UNKNOWN_KAFKA_ERROR("60000"),

    // LLM
    UNKNOWN_ANALYTICS_ERROR("70000"),

    // OTHER
    TEMPORARY_CODE("99999");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }
}
